### ISSUE TITLE
feature: parsing RDF-XML

### ISSUE THREAD

**Issue by theWebalyst** [blake-regalia/graphy.js#27]
Hi Blake,

Any plans to parse XML? I'm thinking it is essential for handling many SPARQL endpoints so wondering if it's likely to be part of graphy at some point.

Thanks

**Comment by blake-regalia** [comment]
This was discussed in #15 a bit. Have you looked into [rdfxml-streaming-parser](https://github.com/rdfjs/rdfxml-streaming-parser.js)? I don't want to duplicate the effort unless it turns out that RDF/XML reading can be significantly outperformed and that there's high enough demand for it. You can even pass graphy DataFactory to that library's constructor to get graphy terms & quads while reading.

**Comment by blake-regalia** [comment]
BTW, I just posted a roadmap for planned features in future releases [here](https://github.com/blake-regalia/graphy.js/blob/master/ROADMAP.md).

**Comment by theWebalyst** [comment]
Thanks for the tip Blake. Quick try of `rdfxml-streaming-parser` is very promising (it just worked!).
